### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by JiminyKroket** [TGIANN/fivem-tgiann-skillbar#1]
This seems like a great release, but there is no indication for how to properly use the system.

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/148929758-87801d75-a1b6-4a3a-ac03-111f087ce0c0.png)

**Comment by JiminyKroket** [comment]
Just like that?

**Comment by TGIANN** [comment]
check readme
